doctrine.configuration_paths: ['app/config/doctrine']

doctrine.db_parameters:
  driver:   'pdo_mysql'
  user:     'root'
  password: '1234'
  dbname:   'game'
  charset:  'UTF8'

services:
  doctrine.setup_configuration:
    factoryStaticMethod: ['Doctrine\ORM\Tools\Setup', 'createAnnotationMetadataConfiguration']
    arguments: ['%doctrine.configuration_paths%']

  doctrine.entity_manager:
    factoryStaticMethod: ['Doctrine\ORM\EntityManager', 'create']
    arguments: ['%doctrine.db_parameters%', '@doctrine.setup_configuration']
    alias: doctrine

  doctrine.connection:
    factoryMethod: ['@doctrine.entity_manager', 'getConnection']
    alias: db_connection
